apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-flask-app
  template:
    metadata:
      labels:
        app: model-flask-app
    spec:
      containers:
      - name: model-flask-app
        image: ishita135/mlops:1
        ports:
        - containerPort: 7860
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: model-flask-app-service
spec:
  selector:
    app: model-flask-app
  ports:
    - protocol: TCP
      port: 7860
      targetPort: 7860
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: model-flask-app-service-api
spec:
  selector:
    app: model-flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort