apiVersion: v1
kind: Service
metadata:
  name: mnist-inference-service
spec:
  selector:
    app: mnist-inference
  ports:
  - protocol: TCP
    port: 80  # External port for accessing the service
    targetPort: 5000  # Port exposed by the containers
  type: LoadBalancer  # Use LoadBalancer type for external access


curl -X POST -H "Content-Type: application/json" -d '{"image": "base64_encoded_image_data"}' http://localhost:5000/predict
